## EDA of Delaware Vets
@xt0fer Kris Younger

looking at a dataset from https://catalog.data.gov/dataset/gravesite-locations-of-veterans-and-beneficiaries-in-delaware-as-of-may-2019

In [2]:
import pandas as pd
import numpy as np

In [3]:
full_set = pd.read_csv("ngl_delaware.csv",header=None,sep='\t')

In [5]:
full_set.head()

,d_first_name,d_mid_name,d_last_name,d_suffix,d_birth_date,d_death_date,section_id,row_num,site_num,cem_name,...,cem_url,cem_phone,relationship,v_first_name,v_mid_name,v_last_name,v_suffix,branch,rank,war
Jesse,L,Williams,Jr,05/23/1964,02/25/2018,G,I,10.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Veteran (Self),Jesse,L,Williams,Jr,US NAVY,ABH1,"GRENADA, PANAMA, PERSIAN GULF",NaN
Lila,M,Childres,NaN,08/25/1931,02/26/2018,C,O,5.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Wife,Dennis,C,Childres,NaN,US AIR FORCE,MSGT,"KOREA, VIETNAM",NaN
Gregory,L,Young,NaN,12/06/1948,10/26/2017,G,G,10.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Veteran (Self),Gregory,L,Young,NaN,US AIR FORCE,MSGT,"GRENADA, LEBANON, VIETNAM",NaN
Paul,B,Littleton,NaN,08/18/1929,10/21/2017,H,M,7.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Veteran (Self),Paul,B,Littleton,NaN,US NAVY,EMS,KOREA,NaN
Allan,D,Stephens,NaN,04/23/1945,10/24/2017,G,G,11.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Veteran (Self),Allan,D,Stephens,NaN,US ARMY,SP4,VIETNAM,NaN

In [6]:
full_set.tail()

,d_first_name,d_mid_name,d_last_name,d_suffix,d_birth_date,d_death_date,section_id,row_num,site_num,cem_name,...,cem_url,cem_phone,relationship,v_first_name,v_mid_name,v_last_name,v_suffix,branch,rank,war
Carl,R,Cartwright,NaN,11/30/1947,10/20/1991,B,M,12.0,DELAWARE VETERANS MEMORIAL CEMETERY,2465 CHESAPEAKE ROAD,...,302-834-8046,Veteran (Self),Carl,NaN,Cartwright,NaN,US ARMY,SP4,VIETNAM,NaN
Nancy,A,Mento,NaN,06/18/1946,06/26/1998,XI,B,9.0,DELAWARE VETERANS MEMORIAL CEMETERY,2465 CHESAPEAKE ROAD,...,302-834-8046,Wife,Samuel,J,Mento,NaN,US ARMY,SFC,KOREA,NaN
Nicholas,NaN,Drahuschak,NaN,12/20/1928,12/28/1991,B,L,15.0,DELAWARE VETERANS MEMORIAL CEMETERY,2465 CHESAPEAKE ROAD,...,302-834-8046,Veteran (Self),Nicholas,NaN,Drahuschak,NaN,US AIR FORCE,A1C,KOREA,NaN
James,F,Leruo,NaN,02/19/1936,03/29/2003,2D,P,16.0,DELAWARE VETERANS MEMORIAL CEMETERY,2465 CHESAPEAKE ROAD,...,302-834-8046,Veteran (Self),James,F,Leruo,NaN,US NAVY,LCDR,KOREA,NaN
Joseph,J,Pecoraro,NaN,05/06/1923,03/18/2012,G,H,7.0,DELAWARE VETERANS MEMORIAL CEMETERY-SUSSEX CO.,26669 Patriots Way,...,302-934-5653,Veteran (Self),Joseph,J,Pecoraro,NaN,US ARMY AIR FORCES,CPL,WORLD WAR II,NaN